import Head from "next/head";
import { Flex, Heading, Image, Button } from '@chakra-ui/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Notiom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex mt = {29} ml = {49}>
        <Image
          boxSize='48px'
          objectFit='cover'
          src='Vector.png'
        />
        <Heading 
          fontFamily={`"DM Sans", sans-serif`} 
          color="#545454" 
          fontSize={40} 
          ml = {5}
          w = {142}
          >
          Notiom
        </Heading>
      </Flex>
    </>
  );
}
